---
language: node_js

os:
  - linux
  - osx
  - windows

node_js:
  - "8"
  - "12"

cache:
  directories:
    - "node_modules"

env:
  - DEBUG=*

install:
  - npm install
  - pip install mkdocs

script:
  - npm run-script testci

after_success:
  - if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./.site_build.sh ; fi
  - if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./.site_deploy.sh ; fi
