image:
  - Visual Studio 2019
  - Ubuntu
  - macOS
  
# branches to build
branches:
  # whitelist
  only:
    - master

install:
- npm install sharp@latest --save 
- npm install

test_script:
- npm test

build: off
